### ISSUE TITLE
Website relaunch: Content

### ISSUE THREAD

**Issue by ffffux** [gr2m/milestones#31]
- [X] outline all content according to new URL structure
- [x] landing page: new Hoodie Intro
- [x] what is Hoodie: intro, technology, case studies
- [x] transparency / status: "Current version: 0.3.2 – 76 commits and 3 releases by 17 comitters” (or similar) - see https://github.com/gr2m/milestones/issues/3
- [x] contribute to Hoodie: list of entry points for contributors (non-coders and devs), sponsoring, talks etc.
- [x] help: entry point to FAQ, contact, but report etc.
- [x] bug: how and where to report a bug
- [x] events: list of upcoming Hoodie- and related talks and events incl. map
- [X] media: list of all Hoodie- and related talks, podcasts, … (videos, slides etc.)
- [x] about: philosophy, community, contributors, initiatives + side projects
- [x] friends
- [x] special page
- [x] merchandising page
- [x] contact: all contact details
- [x] Code of Conduct
- [x] Styleguide
- [x] Imprint
- [x] Blog (no new content)
- [x] Page Footer: Licenses
- [x] your own Hoodie talk: talk kit
- [x] Launch date: prepare blog post about work on relaunch, ideas behind, short walkthrough
- [x] update http://stackoverflow.com/tags/hoodie/info
- [x] translate privacy policy
- [x] discuss licenses with non-coding people involved
- [x] set up navigation
- [x] set up colour-coding

list to be continued

**Comment by gr2m** [comment]
as discussed with @ffffux, moving open issues to #39
