### ISSUE TITLE
Render problem

### ISSUE THREAD

**Issue by nicknikolov** [gr2m/milestones#43]
Hi, tried to fork this, put my own github repo URL and push to gh pages but it doesn't seem to want to render properly.

It looks like this:
http://groupnoto.github.io/milestones/
Here is screenshot:
![screen shot 2015-02-08 at 10 30 10](https://cloud.githubusercontent.com/assets/1440420/6096213/7d922c1a-af7d-11e4-9734-7c6f84af68b6.png)

I'm not very experienced in web stuff so I'm sure I'm forgetting something.
Thanks!
Nick

**Comment by gr2m** [comment]
Hm, I tried it locally and it works fine. What you have to do is only adjust the `master` branch, don't do any edits in the `gh-pages ` branch at all.

Try the following:

1. `git checkout master`
2. change `var repoUrl = 'https://github.com/gr2m/milestones';` to the repo you want the issues to be loaded from in `src/js/app.js`
3. run `grunt serve`, open the local server at http://localhost:9000, to make sure it works
4. If all looks good, run `grunt deploy`

Let me know if that works for you.

And thanks for getting in touch, I'll make the readme more clear once we got it working for you

**Comment by nicknikolov** [comment]
Hi, 

same thing happens when I run it locally. With your repo and mine as well. 
I really don't know what's going on. Perhaps some dependancy I missed to install?
I've installed only compass as gem to run as that's the only thing Grunt complained about.

**Comment by gr2m** [comment]
@nicknikolov are you sure you are in the `master` branch, not in `gh-pages`? I just did that locally myself and it worked just fine

**Comment by nicknikolov** [comment]
Yes, I cloned again, npm install, bower install and grunt serve locally. Doesn't work with your repo either. 
![screen shot 2015-02-08 at 15 57 05](https://cloud.githubusercontent.com/assets/1440420/6097190/27223f68-afab-11e4-9f4a-5d049577ea81.png)
When I clone there is no gh pages branch yet. (Before I do grunt deploy that is)

**Comment by gr2m** [comment]
okay, I can reproduce it now, thanks for your patience :) I'll get back to as soon as I found out what's going on here

**Comment by nicknikolov** [comment]
cool, thanks!

**Comment by gr2m** [comment]
Okay, problem was underscore ... there was a new version, that broke the behavior, without bumping the major version ... I could have guessed that earlier. Anyway, when you set it up again, it should work now

**Comment by nicknikolov** [comment]
Dope! Works now. Thanks for the help!
