### ISSUE TITLE
Implement account client API

### ISSUE THREAD

**Issue by gr2m** [gr2m/milestones#62]
- [x] session (sign in, check session, sign out)
- [x] account (sign up, get / update / destroy account)
- [x] profile (get / update profile)
- [x] requests https://github.com/hoodiehq/hoodie-client-account/issues/12

**Comment by gr2m** [comment]
^5 @HipsterBrown

**Comment by gr2m** [comment]
reopened, forgot about https://github.com/hoodiehq/hoodie-client-account/issues/12 :)

**Comment by HipsterBrown** [comment]
So close!
