### ISSUE TITLE
Fix all known issues for Hoodie Camp Release

### ISSUE THREAD

**Issue by gr2m** [gr2m/milestones#88]
follow up for https://github.com/gr2m/milestones/issues/87

<a name="ready"></a>
### Ready 

- [x] https://github.com/hoodiehq/hoodie-client-account/issues/50  
      `hoodie.account.signOut()` must resolve with account properties, currently is undefined
- [x] https://github.com/hoodiehq/hoodie-server-account/issues/52  
      PUT /session to return 401 Unauthorized error when user cannot be found
- [x] https://github.com/hoodiehq/hoodie-server-account/issues/53  
      Implement PATCH /session/account route
- [x] https://github.com/hoodiehq/hoodie-client-account/issues/52  
      Implement `hoodie.account.update(changedProperties)`
- [x] https://github.com/hoodiehq/hoodie-client-account/issues/53  
      implement `hoodie.account.destroy()`
- [x] https://github.com/hoodiehq/hoodie-client-account/issues/54  
      `hoodie.account.fetch()`, `.update()`, `.profile.fetch()` and `.profile.update()` should fail with UnauthenticatedError if session is invalid, but currently fails with "Not FoundError"
- [x] https://github.com/hoodiehq/hoodie-client-account/issues/56  
      Implement `hoodie.account.isUnauthenticated()`
- [x] https://github.com/hoodiehq/hoodie-client-account/issues/57  
      Implement `reauthenticate` event
- [x] https://github.com/hoodiehq/hoodie-client-store/issues/69  
      Return custom Conflict error
- [x] https://github.com/hoodiehq/hoodie-client-store/issues/70  
      Return custom Not Found error
- [x] https://github.com/hoodiehq/hoodie-client-store/issues/71  
      Implement `hoodie.store.isPersistent()`
- [x] https://github.com/hoodiehq/hoodie-client/issues/44  
      Reset `hoodie.store` correctly on `signout` event
- [x] https://github.com/hoodiehq/hoodie-client/issues/45  
      Reset `hoodie.store` on `signin` event
- [x] https://github.com/hoodiehq/hoodie-client-account/issues/65  
       pass options.hooks to signup / signin / signout events
- [x] https://github.com/hoodiehq/hoodie-client-account/issues/69  
       trigger "update" event when account.update succeeds
- [x] https://github.com/hoodiehq/hoodie-client-account/issues/70  
       renew session after changing username / password
- [x] https://github.com/hoodiehq/hoodie-client/issues/54  
       call hoodie.store.connect() on page load if user is signed in
- [x] https://github.com/hoodiehq/hoodie-server-account/issues/79  
       Implement username change
- [x] https://github.com/hoodiehq/hoodie-client-account/issues/75  
       `account.update`: set session ID from `x-set-session` response header
- [x] https://github.com/hoodiehq/hoodie-server-account/issues/80  
       PATCH /session/account: respond with `x-set-session` header
- [x] https://github.com/hoodiehq/hoodie-server-account/issues/81
       GET, PATCH, DELETE /session/account sould respond with 401 Invalid session, not 404 Not found
- [x] https://github.com/hoodiehq/hoodie-server-store/issues/12  
       Store Server: Proxy to PouchDB instance
- [x] https://github.com/hoodiehq/hoodie-server/issues/459  
       rename `/hoodie/bundle.js` to `/hoodie/client.js`
- [x] https://github.com/hoodiehq/hoodie-server/issues/436  
       rename `/www` folder to `/public`
- [x] https://github.com/hoodiehq/hoodie/issues/458  
     simplify Internal Module Architecture
- [x] https://github.com/hoodiehq/hoodie-server/issues/478  
     make the Hoodie fallback webapp more helpful
- [x] https://github.com/hoodiehq/hoodie-app-tracker/issues/19  
     Tracker app: items are disappearing after I log out and log back in

<a name="needs instructions"></a>
### Needs instructions

- [ ] https://github.com/hoodiehq/hoodie/issues/457  
      unify test setup
- [ ] https://github.com/hoodiehq/account-json-api/issues/14  
      remove /session/account from spec
- [ ] https://github.com/hoodiehq/hoodie-server-account/issues/83  
     Inconsistencies between implementation and API spec

<a name="discussion"></a>
### Discussion

- [ ] https://github.com/hoodiehq/hoodie-client/issues/62  
       how to add a .createdBy property automagically to all documents created with hoodie.store.add?
- [ ] https://github.com/hoodiehq/hoodie/issues/485  
       rename `bearer` in our `Authorization` header to `session`, because that’s what it is, and we don’t use bearer tokens anywhere else in our code. It’s unnecessary confusing. So instead of `Authorization: bearer sessionid123` header, we would have `Authorization: session sessionid123`

**Comment by gr2m** [comment]
@codyzu these 3 issues are all related to username change:

- https://github.com/hoodiehq/hoodie-account-server/issues/79
- https://github.com/hoodiehq/hoodie-account-client/issues/75
- https://github.com/hoodiehq/hoodie-account-server/issues/80

here is some background information on it:
https://dl.dropboxusercontent.com/u/732913/hoodie/2016-04-21-username-change-code-background-info.mov

You can un-skip [this test](https://github.com/hoodiehq/hoodie-account/blob/master/test/integration.js#L206) in hoodiehq/hoodie-account to make sure it all works together. To set it up locally, git clone the three repos, then run `npm link` in the `hoodie-account-server` and `hoodie-account-client` folder, then run `npm link @hoodie/account-server` and `npm link `@hoodie/account-client` in the `hoodie-account` folder. Now you can do changes in the server and the client, and immediately test it when restarting the server or the tests in `hoodie-server`

Let me know if you want to give this a try, or if you have any farther questions

**Comment by codyzu** [comment]
@gr2m I'll start looking at the details today... I won't have any results until wednesday (when I have some hours reserved for this) :+1:

**Comment by gr2m** [comment]
okay, wow, I guess that’s it :) The remaining issues can be done as part of the next release :)
