### ISSUE TITLE
Update all docs & tutorials to new Hoodie

### ISSUE THREAD

**Issue by gr2m** [gr2m/milestones#92]

**Comment by austinjreilly** [comment]
If I understood correctly, the [API](https://github.com/hoodiehq/hoodie-account-client#api) section of the hoodie-account-client README is up to date, but the [documentation site](http://docs.hood.ie/en/techdocs/api/client/hoodie.account.html) is not. 

The documentation on the site needs to be updated to match the README.

As we talked about last week, I think there are few first steps to get started:

1. Make a list of all pages and/or sections that need to be updated.
2. Make a banner or indicator of some kind to make it clear that the content on that page references the old version of Hoodie.
3. Update the documentation to reflect the changes in Hoodie Camp.
4. Remove banner/indicator that page references old documentation. 

Does that make sense?

Also, it doesn't look like the #docs channel in Slack is very active. Is most of that conversation happening in the #general channel, if it's happening at all?

**Comment by gr2m** [comment]
thanks for taking the initiative @austinjreilly. 

> If I understood correctly, the API section of the hoodie-account-client README is up to date, but the documentation site is not. 

Yes, that’s correct.

> Make a list of all pages and/or sections that need to be updated

Good first step. :+1: 

> Make a banner or indicator of some kind to make it clear that the content on that page references the old version of Hoodie.

I’d suggest we need two things

1. A banner that we can show if the displayed content is still the old version, linking to an issue that describes what needs to be done.
2. A banner / link of some kind that we can use to direct people to the old version of the documentation. 

> Update the documentation to reflect the changes in Hoodie Camp.

It’d start by creating a new branch `camp` where we invite everyone to work together on this.

> Remove banner/indicator that page references old documentation

As mentioned above, I would not entirely remove the old version, there will be people still using it for some time.

> it doesn't look like the #docs channel in Slack is very active

Let’s reactivate it.

**Comment by gr2m** [comment]
did you setup the documentation page locally yet? I’ve just updated https://github.com/hoodiehq/documentation#running-the-doc-site-locally – let me know if that works for you

**Comment by austinjreilly** [comment]
I actually did have the documentation page running locally last night, but I pulled this morning and got it working again. 

I'll get started on these tasks tonight.

**Comment by austinjreilly** [comment]
Is everything that needs to be updated on the [api/client/hoodie.account.html page(http://docs.hood.ie/en/techdocs/api/client/hoodie.account.html)?

I began comparing the headings of the [README ](https://github.com/hoodiehq/hoodie-account-client#api) with the contents of that page, and it looks like there isn't a lot of overlap at all. That, combined with your comment that some people will continue using the old API makes me think that there should be some kind of pre-Camp subdirectory on the docs site where the old documentation is kept.

**Comment by gr2m** [comment]
Hey @austinjreilly are you still interested in helping? We could really use a hand and someone who can take more ownership to finish the docs. The basic setup is done, and when you go to http://docs.hood.ie/ you see the link to the "Camp Release" in the header. The source files are all here: https://github.com/hoodiehq/documentation/tree/gh-pages/camp

It’s one of our major concerns right now to finish the documentation and the tutorials, so that we can deprecate the old docs, the current state is very confusing to people and creates a lot of extra support efforts on the team’s shoulders as we have to support both versions right now

Please let me know if you’re still interested, I’m happy to walk you through

**Comment by gr2m** [comment]
Hey all, I would like to move our docs to readthedocs.org. Please see my issue on https://github.com/hoodiehq/discussion/issues/109 and let me know what you think

**Comment by gr2m** [comment]
that’s done 👍
